# Generated by Django 6.0.1 on 2026-08-10 11:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carouselad_media_file_neutral_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselad',
            name='media_file',
            field=models.FileField(blank=True, upload_to='carousel-media/', validators=[core.models._validate_media_file]),
        ),
    ]
