# Generated by Django 6.0.1 on 2026-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_and_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountannouncement',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Discount Announcement', 'verbose_name_plural': 'Discount Announcements'},
        ),
        migrations.AddField(
            model_name='discountannouncement',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls slide order in the carousel. Lower numbers appear first.'),
        ),
    ]
