# Generated by Django 6.0.1 on 2026-09-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_discount_order_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Care Category',
                'verbose_name_plural': 'Home Care Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomeCareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField()),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, upload_to='homecare-products/')),
                ('external_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.homecarecategory')),
            ],
            options={
                'verbose_name': 'Home Care Product',
                'verbose_name_plural': 'Home Care Products',
                'ordering': ['name'],
            },
        ),
    ]
