# Generated by Django 6.0.1 on 2026-09-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homecare_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCareProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homecare-products/extra/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='core.homecareproduct')),
            ],
            options={
                'verbose_name': 'Home Care Product Image',
                'verbose_name_plural': 'Home Care Product Images',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/extra/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='core.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
