# Generated by Django 6.0.1 on 2026-09-24 15:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_extra_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCareCarouselAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('cta_text', models.CharField(blank=True, default='Explore', max_length=100)),
                ('cta_href', models.CharField(blank=True, default='#products', max_length=200)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('media_file', models.FileField(blank=True, upload_to='homecare-carousel-media/', validators=[core.models._validate_media_file])),
                ('external_image_url', models.URLField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=5)),
                ('media_fit', models.CharField(choices=[('cover', 'Cover — fill the hero, crop if needed (best for landscape)'), ('contain', 'Contain — show the entire image with no crop (best for portrait)')], default='cover', help_text='How the media fits inside the hero. "cover" for landscape (full-bleed). "contain" for portrait (whole image visible).', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Care Carousel Ad',
                'verbose_name_plural': 'Home Care Carousel Ads',
                'ordering': ['order'],
            },
        ),
    ]
