# Generated by Django 6.0.1 on 2026-08-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('distributor_code', models.CharField(db_index=True, help_text='Unique alphanumeric code assigned by admin (e.g. DIST001). Saved as uppercase. Used as login username.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to block login without deleting the account.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
                'ordering': ['distributor_code'],
            },
        ),
    ]
